#!/bin/bash
# Update laserjet/jetdirect LCDs with the IP of the printer
# first and only argument should be an IP or subnet (CIDR notation) to scan for printers.
# requires nmap and gawk>=3.1
nmap -p 9100 ${1:?} -oG - | gawk '
/Host: .* 9100.open.tcp/ {
  IP=$2;
  socket="/inet/tcp/0/" IP "/9100";
  printf ("\033%%-12345X@PJL RDYMSG DISPLAY = \042%s\042\r\n\033%%-12345X\r\n", IP) > socket;
  close(socket);
}'
