#!/bin/bash
DELAY=30
BR="br -c E"
# turn light on, but dim all the way
$BR --dim=-12,3
# First, up the brightness two steps.
$BR --dim=2,3
# The rest of the steps are one step brighter.
for a in 3 4 5 6 7 8 9 10 11 12; do
  sleep $DELAY
  $BR --dim=1,3
done
